name: interact with Github API
on: 
  pull_request:

jobs:
  create-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Install curl
        shell: bash
        run: |
          sudo apt update && sudo apt install curl -y
      - name: Shorten SHA
        id: short_sha
        run: echo "sha_short=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"
      - name: Request Github API
        shell: bash
        run: |
            echo "https://api.github.com/repos/${{ github.repository }}/issues"
            curl --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/issues \
            --header 'authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}' \
            --header 'content-type: application/json' \
            --data '{
              "title": "Automated issue for commit: ${{ steps.short_sha.outputs.sha_short }}",
              "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ steps.short_sha.outputs.sha_short }}_."
              }' \
            --fail
